In [27]:
# 01
import numpy as np
print(np.__version__)



1.18.4


In [2]:
# 02
arr = np.arange(10)
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [3]:
# 03
np.full((3, 3), True, dtype=bool)

array([[ True,  True,  True],
       [ True,  True,  True],
       [ True,  True,  True]])

In [4]:
# 04
arr = np.arange(10)
arr[arr % 2 == 1]

array([1, 3, 5, 7, 9])

In [7]:
# 05
arr = np.arange(10)
arr[arr % 2 ==1] = -1
arr

array([ 0, -1,  2, -1,  4, -1,  6, -1,  8, -1])

In [8]:
# 06
arr = np.arange(10)
out = np.where(arr % 2 == 1, -1, arr)
print(arr)
out



[0 1 2 3 4 5 6 7 8 9]


array([ 0, -1,  2, -1,  4, -1,  6, -1,  8, -1])

In [9]:
# 07
arr = np.arange(10)
arr.reshape(2, -1)



array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [10]:
# 08 vertically
a = np.arange(10).reshape(2, -1)
b = np.repeat(1, 10).reshape(2, -1)
np.concatenate([a, b], axis=0)


array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]])

In [5]:
# 09 horizontally
a = np.arange(10).reshape(2, -1)
b = np.repeat(1, 10).reshape(2, -1)
np.concatenate([a, b], axis=1)



array([[0, 1, 2, 3, 4, 1, 1, 1, 1, 1],
       [5, 6, 7, 8, 9, 1, 1, 1, 1, 1]])

In [13]:
# 10
a = np.array([1, 2, 3])
np.r_[np.repeat(a, 3), np.tile(a, 3)]



array([1, 1, 1, 2, 2, 2, 3, 3, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3])

In [14]:
# 11
a = np.array([1,2,3,2,3,4,3,4,5,6])
b = np.array([7,2,10,2,7,4,9,4,9,8])
np.intersect1d(a,b)



array([2, 4])

In [15]:
# 12
a = np.array([1,2,3,4,5])
b = np.array([5,6,7,8,9])
np.setdiff1d(a, b)



array([1, 2, 3, 4])

In [16]:
# 13
a = np.array([1,2,3,2,3,4,3,4,5,6])
b = np.array([7,2,10,2,7,4,9,4,9,8])
np.where(a == b)



(array([1, 3, 5, 7]),)

In [21]:
# 14
a = np.arange(15)
index = np.where((a >= 5) & (a <= 10))
a[index]


array([ 5,  6,  7,  8,  9, 10])

In [22]:
# 15
def maxx(x, y):
    """Get the maximum of two items"""
    if x >= y:
        return x
    else:
        return y

pair_max = np.vectorize(maxx, otypes=[float])

a = np.array([5, 7, 9, 8, 6, 4, 5])
b = np.array([6, 3, 4, 8, 9, 7, 1])

pair_max(a, b)




array([6., 7., 9., 8., 9., 7., 5.])

In [26]:
# 16 swap cols
arr = np.arange(9).reshape(3, 3)
arr
arr[:, [1, 0, 2]]
# arr[:, [0, 1, 2]]

array([[1, 0, 2],
       [4, 3, 5],
       [7, 6, 8]])

In [28]:
# 17 swap rows
arr = np.arange(9).reshape(3,3)
arr
arr[[1,0,2], :]



array([[3, 4, 5],
       [0, 1, 2],
       [6, 7, 8]])

In [32]:
# 18 reverse rows
arr = np.arange(9).reshape(3,3)
arr[::-1]


array([[6, 7, 8],
       [3, 4, 5],
       [0, 1, 2]])

In [33]:
# 19 reverse cols
arr = np.arange(9).reshape(3,3)
arr[:, ::-1]



array([[2, 1, 0],
       [5, 4, 3],
       [8, 7, 6]])

In [34]:
# 20
rand_arr = np.random.uniform(5,10, size=(5,3))
print(rand_arr)



[[6.56900181 6.66601619 6.15055593]
 [8.01053148 5.18889186 6.01997404]
 [9.28631877 8.92483377 8.63646745]
 [7.74155334 7.30423345 6.24254475]
 [5.41094756 7.24686857 9.24231017]]


In [36]:
# 21
rand_arr = np.random.random([5,3])
np.set_printoptions(precision=3)
rand_arr[:4]



array([[0.058, 0.719, 0.217],
       [0.595, 0.78 , 0.469],
       [0.104, 0.035, 0.718],
       [0.321, 0.868, 0.783]])

In [37]:
# 22
np.set_printoptions(suppress=False)

# Create the random array
np.random.seed(100)
rand_arr = np.random.random([3,3])/1e3
rand_arr




array([[5.434e-04, 2.784e-04, 4.245e-04],
       [8.448e-04, 4.719e-06, 1.216e-04],
       [6.707e-04, 8.259e-04, 1.367e-04]])

In [38]:
# 23
np.set_printoptions(threshold=6)
a = np.arange(15)
a



array([ 0,  1,  2, ..., 12, 13, 14])

In [6]:
# 24
np.set_printoptions(threshold=6)
a = np.arange(15)
# np.set_printoptions(threshold=np.nan)
a



array([ 0,  1,  2, ..., 12, 13, 14])

In [4]:
# 25
url = 'https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data'
iris = np.genfromtxt(url, delimiter=',', dtype='object')
names = ('sepallength', 'sepalwidth', 'petallength', 'petalwidth', 'species')

# Print the first 3 rows
iris[:3]



array([[b'5.1', b'3.5', b'1.4', b'0.2', b'Iris-setosa'],
       [b'4.9', b'3.0', b'1.4', b'0.2', b'Iris-setosa'],
       [b'4.7', b'3.2', b'1.3', b'0.2', b'Iris-setosa']], dtype=object)

In [26]:
# pandas 01
import pandas as pd

df = pd.read_csv("countries.csv")
df



Name     People     Area   BIP Currency
0   Germany   82521653   357385  3466      EUR
1     Japan  126045000   377835  4938      YEN
2    Canada   36503097  9984670  1529      CAD
3     Italy   60501718   301338  1850      EUR
4  Brazilia  208360000  8515770  1798     REAL

In [25]:
# pandas 02
print(df.describe())




             People          Area         BIP
count  5.000000e+00  5.000000e+00     5.00000
mean   1.027863e+08  3.907400e+06  2716.20000
std    6.759970e+07  4.904957e+06  1457.86083
min    3.650310e+07  3.013380e+05  1529.00000
25%    6.050172e+07  3.573850e+05  1798.00000
50%    8.252165e+07  3.778350e+05  1850.00000
75%    1.260450e+08  8.515770e+06  3466.00000
max    2.083600e+08  9.984670e+06  4938.00000


In [3]:
# pandas 02
df.shape

(5, 5)

In [4]:
# pandas 02
df.columns

Index(['Name', 'People', 'Area', 'BIP', 'Currency'], dtype='object')

In [5]:
# pandas 02
df.loc["Germany"]

KeyError: 'Germany'

In [19]:
# pandas 03
df.tail(4)

Name     People     Area   BIP Currency
1     Japan  126045000   377835  4938      YEN
2    Canada   36503097  9984670  1529      CAD
3     Italy   60501718   301338  1850      EUR
4  Brazilia  208360000  8515770  1798     REAL

In [20]:
# pandas 04
df.query('Currency == "EUR"')

Name    People    Area   BIP Currency
0  Germany  82521653  357385  3466      EUR
3    Italy  60501718  301338  1850      EUR

In [22]:
# pandas 05
newDataFrame = df[['Name','Currency']] 
newDataFrame

Name Currency
0   Germany      EUR
1     Japan      YEN
2    Canada      CAD
3     Italy      EUR
4  Brazilia     REAL

In [24]:
# pandas 06
dataFrameOne = df.loc[(df['BIP'] > 2000)]
dataFrameOne

Name     People    Area   BIP Currency
0  Germany   82521653  357385  3466      EUR
1    Japan  126045000  377835  4938      YEN

In [8]:
# pandas 07
df2 = df.loc[((df['People'] > 50000000) & (df['People'] < 150000000))]
df2

Name     People    Area   BIP Currency
0  Germany   82521653  357385  3466      EUR
1    Japan  126045000  377835  4938      YEN
3    Italy   60501718  301338  1850      EUR

In [32]:
# pandas 08
df3 = df.rename(columns={'BIP': 'Bip'})
print(df3)


       Name     People     Area   Bip Currency
0   Germany   82521653   357385  3466      EUR
1     Japan  126045000   377835  4938      YEN
2    Canada   36503097  9984670  1529      CAD
3     Italy   60501718   301338  1850      EUR
4  Brazilia  208360000  8515770  1798     REAL


In [35]:
# pandas 09
df4 = df['BIP'].sum()
df4


13581

In [36]:
# pandas 10
df5 = df['People'].mean()
df5

102786293.6

In [37]:
# pandas 11
df.sort_values('Name')


Name     People     Area   BIP Currency
4  Brazilia  208360000  8515770  1798     REAL
2    Canada   36503097  9984670  1529      CAD
0   Germany   82521653   357385  3466      EUR
3     Italy   60501718   301338  1850      EUR
1     Japan  126045000   377835  4938      YEN

In [ ]:
# pandas 12
